### ISSUE TITLE
JAXB episode compilation with include does not work

### ISSUE THREAD

**Issue by the-foreigner** [highsource/jaxb-tools#1]
I have 2 schemas A, B. I'm reusing some A elements in B. I do not use namespaces.

I'm using

```
<groupId>org.jvnet.jaxb2.maven2</groupId>
<artifactId>maven-jaxb2-plugin</artifactId>
<version>0.9.0</version>
```

I have have defined an inclusion of schema A in schema B as:

```
<xs:include schemaLocation="classpath:my.schema.A.xsd"/>
```

and the catalog as

```
REWRITE_SYSTEM "classpath:my.schema.A.xsd" "maven:my.schema:schema-a!/A.xsd"
```

The jaxb configuration goes:

```
<configuration>
    <generatePackage>my.schema.b</generatePackage>
    <schemaIncludes>
        <includes>B.xsd</includes>
    </schemaIncludes>
    <episodes>
        <episode>
            <groupId>my.schema</groupId>
            <artifactId>schema-a</artifactId>
        </episode>
    </episodes>
    <catalog>src/main/catalog/catalog.cat</catalog>
</configuration>
```

The issue is that whenever I specify the episode dependency the schema does not generate any classes even though it contains some B elements I want to generate the classes for.

```
[INFO] Parsing input schema(s)...
[INFO] Compiling input schema(s)...
[INFO] Cleaning package directories.
[INFO] Finished execution.
```

When I remove the episode it works well and generates classes for schema A as well - which I indeed want to avoid.

Do you have any suggestions?

A sample was published in [Jaxb episodic compilation](https://github.com/the-foreigner/jaxb-episodic-compilation)

**Comment by gatman** [comment]
I know this is closed but there is a third option that worked for me.  You can use the replacer plugin to replace the map="false" with map="true"
