### ISSUE TITLE
scanDependenciesForBindings does not scan project dependencies within eclipse

### ISSUE THREAD

**Issue by Newtopian** [highsource/jaxb-tools#100]
Perhaps I miunderstood the use of scanDependenciesForBindings but I was under the impression it would automagically include bindings (xjb) files from other projects in the current one.  Much like the useDependenciesAsEpisodes option does for included xsd's already generated code from other projects.

However when doing so I get the following error 

`Unable to read the artifact JAR file [C:\home\_eclipseWorkspace\***\target\classes].`

Indicating it is explicitely expecting a jar file as a dependency.  since the project is open in the same workspace Maven added it as a project dependency and points the the class files instead.

The issue is easily circumveened however by adding explicit dependency to the xjb file in the bindings section when I can add DependencyResource. In this case the bindings file is properly resolved and all is good. 

Would have been nice though to have the plugin do the heavy lifting for me and automatically make all bindings available from all dependencies (jar or project).

**Comment by highsource** [comment]
The problem is that this scanning only expects JAR files, not directories. That a dependency can be a directory is an Eclipse/m2e feature, not native Maven feature.

Nevertheless, it can be done.

**Comment by laurentschoelens** [comment]
Hello @Newtopian 
Better late than never, I'm currently working on this issue. Should be solved in next release
