### ISSUE TITLE
Binding not always applied in Eclipse

### ISSUE THREAD

**Issue by nils-christian** [highsource/jaxb-tools#182]
Hi,

We are having following situation:
* We have a jar-File containing the xsd.
* We have a project which uses this jar in the maven-jaxb2-plugin (via dependencyResource).
* The same project contains also a xjb which references the xsd schema.

Now it seems that the binding file is not always applied. When I perform an "update maven project" from within Eclipse, the binding is not applied. If I open the pom.xml, change something and save it, the binding is applied. 

From what we can tell it seems that the plugin is actually executed twice. The first run does not have the binding and the second run has it. But the classes are not generated, as the plugin doesn't recognize any changes in the second run. We tried to use the forceRegenerate property, but it leads to the expected issues with the infinite build loops in Eclipse.

Any hints on this topic?

Thanks and best regards

  Nils

**Comment by laurentschoelens** [comment]
Hi @nils-christian 
We are currently doing housekeeping on issues.
Do you still have the problem ?
Could you provide more details ? Version of the plugin used, sample projects, version of eclipse used...
It seems to be a problem but hard to find the rootcause without more details.
Feel free to comment and post more details you can share with us

**Comment by laurentschoelens** [comment]
@nils-christian : thanks for your answer. Closing as you suggest
