### ISSUE TITLE
generated source is not adding in build path 

### ISSUE THREAD

**Issue by praveen-anjha** [highsource/jaxb-tools#184]
I am trying to generate multiple schema in different folder but only xjc folder is adding in build path not others (xjc08 and xjc09)

![4Ajec](https://user-images.githubusercontent.com/56357828/67851166-be6f1200-fb01-11e9-80e5-a566b3c2ba4a.png)
          
Below is my pom.xml:

                  <plugin>
				<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
				<version>0.14.0</version>
				<executions>
					<execution>
						<id>schema-generate</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<schemaDirectory>src/main/resources</schemaDirectory>
							<schemaIncludes>
								<include>Msg.xsd</include>
							</schemaIncludes>
							<generatePackage>com.model</generatePackage>
							<generateDirectory>${project.build.directory}/generated-sources/xjc</generateDirectory>
							

						</configuration>

					</execution>
					  <execution>
						<id>schema2-generate</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<schemaDirectory>src/main/resources</schemaDirectory>
							<schemaIncludes>
								<include>test1.xsd</include>
							</schemaIncludes>
							<generatePackage>com.modelOne</generatePackage>
							<generateDirectory>${project.build.directory}/generated-sources/xjc09</generateDirectory>

						</configuration>
					</execution>
					<execution>
						<id>schema3-generate</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<schemaDirectory>src/main/resources</schemaDirectory>
							<schemaIncludes>
								<include>test2.xsd</include>
							</schemaIncludes>
 							<generatePackage>com.modeTwo</generatePackage>
 							<generateDirectory>${project.build.directory}/generated-sources/xjc08</generateDirectory>

						</configuration>
					</execution>  
				</executions>
			</plugin>
		</plugins>
	</build>

**Comment by praveen-anjha** [comment]
@highsource  Could you advise

**Comment by highsource** [comment]
Can't reproduce.

Here's the test project:

https://github.com/highsource/maven-jaxb2-plugin-support/tree/master/m/multiple-schemas

After importing this as Maven project in Eclipse, I get:

![image](https://user-images.githubusercontent.com/6707996/67893539-0704ea80-fb57-11e9-92b3-88c79f6b170f.png)

All three generate directories are added to the build path just fine.

**Comment by highsource** [comment]
Check the Maven console in Eclipse. Does it show any problems?

When you run `mvn clean install` from the command line, are the classes generated?  
Are they then compiled to `target/classes`?

**Comment by praveen-anjha** [comment]
Yes, It's generated the classes but not adding class path . I have not added jaxb-runtime dependency 
<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<version>2.3.1</version>
		</dependency>

**Comment by aps-dnxt** [comment]
It would be great to be able to set a package prefix. This way classes would be generated with <prefix>.<schema> package directive.

**Comment by laurentschoelens** [comment]
> It would be great to be able to set a package prefix. This way classes would be generated with <prefix>.<schema> package directive.

Hi @aps-dnxt 
What do you mean by 'set a package prefix' ?

**Comment by laurentschoelens** [comment]
@praveen-anjha do you still have any problems with eclipse configuration ?

**Comment by laurentschoelens** [comment]
> > 
> 
> What package will the generated classes belong to? (package x.y.z)
> If we could set the package to x.y.z.generated, it would be great.
> 
> Regards, 
> APS

You can set `generatePackage` plugin option parameter (or the equivalent property) to tell the plugin where to put package under.

```java
        /** 
          * <p> 
          * The generated classes will all be placed under this Java package (xjc's 
          * -p option), unless otherwise specified in the schemas. 
          * </p> 
          * <p> 
          * If left unspecified, the package will be derived from the schemas only. 
          * </p> 
          */ 
         @Parameter(property = "maven.xjc2.generatePackage") 
         private String generatePackage;
```

**Comment by laurentschoelens** [comment]
@aps-dnxt : feel free to open another issue, I don't think this is related to the problem raised by @praveen-anjha 
We will be happy to help you using jaxb-tools (maven-plugin here in my opinion) and fix / enhance it if needed.
