### ISSUE TITLE
Classloaders not being closed for mojo classloaders

### ISSUE THREAD

**Issue by cwholmes** [highsource/jaxb-tools#188]
This classloader is a URLClassloader which does not get closed and is therefore relying on the finalizer to close all open file handles. This is a problem for long running maven processes for large projects.

This should probably be modified to be closed as the finalize method and the finalizer has been deprecated for possible future removal as of jdk9.

https://github.com/highsource/maven-jaxb2-plugin/blob/master/plugin-core/src/main/java/org/jvnet/jaxb2/maven2/RawXJC2Mojo.java#L312

**Comment by laurentschoelens** [comment]
New file location
https://github.com/highsource/jaxb-tools/blob/master/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java#L312

We'll look if introducing `.close` method in finally block will not break anything

**Comment by laurentschoelens** [comment]
@cwholmes 
This will be fixed in 2.0.6 release
