### ISSUE TITLE
How to generate java classes with the @XmlType.namespace property set

### ISSUE THREAD

**Issue by matheusdallrosa** [highsource/jaxb-tools#198]
I want to generate java classes with the value of the @XmlType annotation's property namespace set.
I have read the docs more than once and could not find a config to do this.
And it is actually important because the javax.xml.bind.Marshaller complains that i have
two classes with the same @XmlType.name property value but there is no namespace to help to differentiate.
Of course i can do it manually but it is like 100 classes in total. Thank you.

**Comment by laurentschoelens** [comment]
Hi @matheusdallrosa 

Sorry for the late answer.
Guess you're looking for that : https://github.com/highsource/jaxb-tools/wiki/JAXB2-Namespace-Prefix-Plugin

It's a plugin to help specifying namespace in generated java classes.

If this doesn't solve your problem and it's more about name collision, you should be able to rename one class to specify another name in generated code.

Feel free to come back to us if you still have any problem with the maven-plugin

Regards
