### ISSUE TITLE
Support for jaxb3

### ISSUE THREAD

**Issue by muued** [highsource/jaxb-tools#199]
Hi,
I love this plugin and have been using it for many years. With the release of JAXB 3.0.0, I'm interested whether there are any plans to support it. I'm willing to support the development and have already toyed around some in [my fork](https://github.com/muued/maven-jaxb2-plugin/tree/playground).
As a start, I have tried to gather the relevant changes below.
Please let me know if I can support this project in any way, e.g., by saying something about the desired way to integrate jaxb3 into this project. It seems rather hard to make the `core` and `testing` projects jaxb-version-agnostic because of the different package names and dependency coordinates.

#### expect bindings to be in a new namespace
`<bindings xmlns="https://jakarta.ee/xml/ns/jaxb" version="3.0">...</bindings>`
relevant for `RawXJC2Mojo.java` and `addIfExistsToEpisodeSchemaBindings.xslt`
#### packages
use `jakarta.xml.bind.annotation` instead of `javax.xml.bind.annotation`
use `org.glassfish.jaxb.core.v2.schemagen.episode` instead of `com.sun.xml.bind.v2.schemagen.episode`
#### libraries
use `jakarta.xml.bind:jakarta.xml.bind-api` instead of `javax.xml.bind:jaxb-api`
update all `org.glassfish.jaxb` artifacts to version `3.0.0`

### requirements towards plugin users
binding files need to be updated to the new namespace "https://jakarta.ee/xml/ns/jaxb" and have their version set to "3.0"
`<bindings xmlns="https://jakarta.ee/xml/ns/jaxb" version="3.0">...</bindings>`
as far as I can tell, the xjc subnamespace hasn't changed

use an updated jaxb runtime, e.g.
```
<dependency>
  <groupId>com.sun.xml.bind</groupId>
  <artifactId>jaxb-impl</artifactId>
  <version>3.0.0</version>
</dependency>
```

**Comment by grv87** [comment]
BTW, I've successfully upgraded [jaxb-visitor](https://github.com/massfords/jaxb-visitor) plugin to JAXB v3, using **current** maven-jaxb2-plugin-testing v0.14.0.

The only problem I experience is

```
[warn] Class [com.sun.tools.xjc.reader.xmlschema.bindinfo.package-info] is missing the [javax.xml.bind.annotation.XmlSchema] annotation. Processing bindings will probably fail.
```

**Comment by dmak** [comment]
> UPD: [jaxb2-basics](https://github.com/highsource/jaxb2-basics) uses current version for JAXB3 too

Minor addendum: As for today `jax2-basics` you point to is still on JAXB 2.3.1, and [here is the version](https://github.com/raphw/jaxb2-basics/) which is on JAXB 3.x.

**Comment by bsanchezb** [comment]
Just one comment to be not forgotten when upgrading to JAXB 3.x: _addIfExistsToEpisodeSchemaBindings.xslt_ should be also modified, as it currently does not seem to support JAXB 3 with _https://jakarta.ee/xml/ns/jaxb_ namespace bindings.
I tested _com.evolvedbinary.maven.jvnet:jaxb30-maven-plugin_ fork and this options seems to be not working (receive _"SCD "x-schema::tns" didnt match any schema component"_ error).

**Comment by johnsgithubaccount** [comment]
> Just one comment to be not forgotten when upgrading to JAXB 3.x: addIfExistsToEpisodeSchemaBindings.xslt should be also modified, as it currently does not seem to support JAXB 3 with https://jakarta.ee/xml/ns/jaxb namespace bindings.
I tested com.evolvedbinary.maven.jvnet:jaxb30-maven-plugin fork and this options seems to be not working (receive "SCD "x-schema::tns" didnt match any schema component" error).

The issue appears to be fixed on the main trunk but not yet released in qa build.  

maven-jaxb2-plugin is running an XSLT transform on the episode file after the XJC generation.  

Here is the (fixed) stylesheet used in the XSLT transformation: https://github.com/phax/maven-jaxb2-plugin/blob/master/plugin-core/src/main/resources/org/jvnet/jaxb2/maven2/addIfExistsToEpisodeSchemaBindings.xslt

You can workaround the problem by invoke the stylesheet transformation from your POM

1. Add the addIfExistsToEpisodeSchemaBindings.xslt to your project 
2. Invoke the xml-maven-plugin from your pom to run the stylesheet transformation.  Something like:

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>xml-maven-plugin</artifactId>
				<version>1.0.2</version>
				<executions>
					<execution>
						<goals>
							<goal>transform</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<transformationSets>
						<transformationSet>
							<dir>${project.build.directory}/generated-sources/xjc/META-INF/</dir>
							<stylesheet>src/main/xslt/addIfExistsToEpisodeSchemaBindings.xslt</stylesheet>
							<outputDir>${project.build.directory}/generated-sources/xjc/META-INF/</outputDir>
						</transformationSet>
					</transformationSets>
				</configuration>
			</plugin>

**Comment by laurentschoelens** [comment]
Made a pull request for supporting jaxb3 / jaxb4 https://github.com/highsource/maven-jaxb2-plugin/pull/255

**Comment by mattrpav** [comment]
#389
