### ISSUE TITLE
Situation that requires forceRegenerate. Or is there another way to achieve this?

### ISSUE THREAD

**Issue by vegemite4me** [highsource/jaxb-tools#203]
This is a very useful plugin, please keep up the good work.

In my setup I have two executions, and I have to set forceRegenerate=true to get the second to execute. This results in a warning, as described here: https://github.com/highsource/maven-jaxb2-plugin/wiki/Do-Not-Use-forceRegenerate

This is how I am using the plugin. The two executions are needed because I need XSD to generate classes in two different packages.

```
<build>
  <plugins>
    <plugin>
      <groupId>org.jvnet.jaxb2.maven2</groupId>
      <artifactId>maven-jaxb2-plugin</artifactId>
      <version>0.14.0</version>
      <executions>

        <execution>
          <id>xsd-to-java-first</id>
          <goals>
            <goal>generate</goal>
          </goals>
          <configuration>
            <schemaIncludes>xsd/first.xsd</schemaIncludes>
            <generatePackage>com.example.first</generatePackage>
          </configuration>
        </execution>

        <execution>
          <id>xsd-to-java-second</id>
          <goals>
            <goal>generate</goal>
          </goals>
          <configuration>
            <schemaIncludes>xsd/second.xsd</schemaIncludes>
            <generatePackage>com.example.second</generatePackage>
            <forceRegenerate>true</forceRegenerate>
          </configuration>
        </execution>

      </executions>
```

Is there another way that I can achieve the same thing without setting `forceRegenerate` to true?

**Comment by laurentschoelens** [comment]
Hi @vegemite4me 
Guess you could achieve this using one execution but with binding file specifying the package to be used for each xsd

See https://github.com/highsource/jaxb-tools/wiki/Configure-Target-Packages-in-Binding-Files for example

**Comment by laurentschoelens** [comment]
Hi @vegemite4me 

Does my answer makes it work now ?
If so, feel free to close the issue.

I'll close it in a few days if no more feedback from you.

Regards

**Comment by vegemite4me** [comment]
Thank you so much for answering my question. Unfortunately it was a project from 2 years ago, and I am no longer on that project. For that reason I am unable to confirm your suggestion.

**Comment by laurentschoelens** [comment]
Thanks for quick reply.
Closing as completed
