### ISSUE TITLE
jaxb2-maven-plugin testXjc goal

### ISSUE THREAD

**Issue by Blaxzter** [highsource/jaxb-tools#205]
Hello,

I'm running into issues with the other jaxb2 plugin and tried this one but can't seem to find a feature.

The mentioned textXjc goal of the jaxb2-maven-plugin is able to generate the classes only for test compiles without copying the classes into the finished jar artifact.
Is there any equivalent configuration in this plugin?

I was able to fix the original issue I was having with the other plugin.

**Comment by laurentschoelens** [comment]
Duplicate of #40 
We'll discuss about that and provide plugin this improvment if not complex

**Comment by laurentschoelens** [comment]
@Blaxzter this will be releases as part of 2.0.6 version
Regards
