### ISSUE TITLE
JAXB plugin v3.x roadmap

### ISSUE THREAD

**Issue by mattrpav** [highsource/jaxb-tools#233]
Current plans for v3.x roadmap:

**Features**
1. Release a jakarta compatible v3.x release
2. Migrate to new groupId/artifactId org.jvnet.jaxb/jaxb-maven-plugin (more recent maven standard)
3. Align plugin version with jaxb release version as much as possible
4. Migrate jaxb plugin-plugin projects (and maybe jaxb2-basics) to be child modules of this tree
5. Add toolchain awareness

**Deprecation**
1. JDK 1.6 and 1.7 support
2. Dropping plugin-2.0, 2.1 and 2.2 support.

The goal of this is to make it more straight forward to consume the modules (esp plugin-plugins) and know if versions are compatible in light of the major JEE/Jakarta changes. Support for multiple versions aligning to various jaxb versions (too complicated and confusing to users in light of jakarta change)

Please use this ticket for comments, discussion and questions.

Thanks!

**Comment by DanielGronau** [comment]
Any progress on this?

**Comment by SingingBush** [comment]
The new jakarta packages (JAXB 3 and 4) work with the evolvedbinary fork:

```xml
<plugin>
    <groupId>com.evolvedbinary.maven.jvnet</groupId>
    <artifactId>jaxb30-maven-plugin</artifactId>
    <version>0.15.0</version>
</plugin>
```

There's no point continuing to support the old javax stuff any more. There's already plenty of historic releases that support that. There simply needs to be a _maven-jaxb-plugin_ that works with the newer packages with JDK 11 and above. (note that Jakarta XML Binding 4 requires Java 11 or higher)

**Comment by bsanchezb** [comment]
Hello,

Are there any plans to adopt _jaxb30-maven-plugin_ fork for the main project? I checked the fork, it seems to be working, but I do not want to include it to the project without maintenance.

Maybe have it as a separate branch with Jakarta support? Preferably the support of JDK 8 should not be dropped, as Jakarta 3 supports Java 8.

Best regards,
Aleksandr.

**Comment by mattrpav** [comment]
Yes, jakarta support is coming

**Comment by johnsgithubaccount** [comment]
> The new jakarta packages (JAXB 3 and 4) work with the evolvedbinary fork:

Can you provide the dependencies you used in both the pom dependencies section and in the jaxb30-maven-plugin section to make it work?   

When I provide jaxb 3.x dependencies, the build complains of missing class like javax/xml/bind/JAXBException

**Comment by SingingBush** [comment]
> Can you provide the dependencies you used in both the pom dependencies section and in the jaxb30-maven-plugin section to make it work?

https://github.com/SingingBush/jaxb-example/blob/main/pom.xml

**Comment by vassik** [comment]
Just wondering if this is something which is going to be merged to main or you guys are working on the jakarta support in another place @mattrpav? Also wondering if there are any thoughts on this project here https://github.com/patrodyne/hisrc-higherjaxb or any plans to integrate changes back to the original project?

**Comment by laurentschoelens** [comment]
@mattrpav any news on this ?

**Comment by bsanchezb** [comment]
Hello,

SpringBoot stops OSS support of version 2.7.x at the end of the year. The newer version SpringBoot 3.x comes with Jakarta 4, thus requiring all applications to upgrade to Jakarta namespaces, and the upgrade becomes vital for a lot of users.

Could you please provide with a rough estimate on the planning of when the Jakarta support becomes available?

Thank you!

Best regards,
Aleksandr.

**Comment by mikhail-putilov** [comment]
I know that probably that's not an appropriate place to share it, but I came up with the simplest workaround that got me through the javax -> jakarta problem during working on my project:

Simply add ant replace after the jaxb plugin:
```xml
<build>
        <plugins>
            <plugin>
                <groupId>org.jvnet.jaxb</groupId>
                <artifactId>jaxb-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <configuration>
                            <target>
                                <replace dir="target/generated-sources" value="jakarta.xml.bind">
                                    <include name="**/*.java"/>
                                    <replacetoken>javax.xml.bind</replacetoken>
                                </replace>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
...
```

**Comment by laurentschoelens** [comment]
@mikhail-putilov thanks for sharing this tip.
The big part before migrating to jakarta is currently under review by @mattrpav 
After that we'll be able to provide a version compatible with jakarta

**Comment by titro** [comment]
Any concrete schedule around that? There is no  Spring Boot 2.X support by the end of the year so time is running out....

**Comment by laurentschoelens** [comment]
> Any concrete schedule around that? There is no Spring Boot 2.X support by the end of the year so time is running out....

Hi @titro 

I'll not give you hope of a concrete date since we're still working on bugfixes on the v2 version (which support jaxb 2.3).

But what I can say is that we're doing active work on this and hope to cut 2.0.4 release this week. Then work on jakarta version based on initial PR I provided so we should be able to cut 3.0.0 release very soon.
In the meantime, you should be able to use this workaround https://github.com/highsource/jaxb-tools/issues/233#issuecomment-1632508716

Feel free to come back if you have any problems with it.

**Comment by laurentschoelens** [comment]
Jakarta is coming, the major refactoring is going to land this week and jaxb3 support should come shortly after.
Stay tuned

**Comment by soc** [comment]
Excellent, thank you for the update!

I'll be happy to migrate w3c-schemas and ogc-schemas to Jakarta as soon as your work lands.

**Comment by laurentschoelens** [comment]
> Excellent, thank you for the update!
> 
> I'll be happy to migrate w3c-schemas and ogc-schemas to Jakarta as soon as your work lands.

Annox and jaxb-annotate-plugin are now part of jaxb-tools
Hyperjaxb is on it's way too

**Comment by soc** [comment]
Have you decided whether/if it's possible to keep the existing groupId/domain?

**Comment by laurentschoelens** [comment]
> Have you decided whether/if it's possible to keep the existing groupId/domain?

Didnt understand your point...
All artifacts are now published under `org.jvnet.jaxb`

**Comment by laurentschoelens** [comment]
@soc could you reword / precise your question please ? 😃

**Comment by soc** [comment]
I think you answered my question, thanks. :-)

**Comment by soc** [comment]
I think you answered my question, thanks. :-)

**Comment by laurentschoelens** [comment]
> I think you answered my question, thanks. :-)

And is it good news ? 😀

**Comment by soc** [comment]
It means that from my understanding you managed to get control over the domain, and therefore are able to publish artifacts under the existing coordinates?

**Comment by laurentschoelens** [comment]
> It means that from my understanding you managed to get control over the domain, and therefore are able to publish artifacts under the existing coordinates?

Yes @mattrpav take over maintenance and managed to publish under the main groupId `org.jvnet.jaxb` (will also publish relocation poms to help migration) and I'm new collaborator to the project from few weeks now thanks to him

**Comment by soc** [comment]
FYI: I have published w3c-schemas and ogc-schemas using the hack mentioned in https://github.com/highsource/jaxb-tools/issues/233#issuecomment-1632508716, but will do a proper patch release after JAXB supports 3.x.

**Comment by soc** [comment]
One thing I realized is that [w3c-schemas](https://mvnrepository.com/artifact/org.w3c-schemas), [ogc-schemas](https://mvnrepository.com/artifact/org.ogc-schemas) and [ogc-tools-gml-jts](https://mvnrepository.com/artifact/org.ogc-schemas/ogc-tools-gml-jts) still have hidden dependency on `javax.xml.bind` caused by generated code using `org.jvnet.jaxb2_commons.locator.ObjectLocator` which extends `javax.xml.bind.ValidationEventLocator`.

So hopefully there is also a new release of `jaxb2_commons` to address this.

**Comment by laurentschoelens** [comment]
> One thing I realized is that [w3c-schemas](https://mvnrepository.com/artifact/org.w3c-schemas), [ogc-schemas](https://mvnrepository.com/artifact/org.ogc-schemas) and [ogc-tools-gml-jts](https://mvnrepository.com/artifact/org.ogc-schemas/ogc-tools-gml-jts) still have a hidden dependency on `javax.xml.bind` caused by generated code using `org.jvnet.jaxb2_commons.locator.ObjectLocator` which extends `javax.xml.bind.ValidationEventLocator`.
> 
> So hopefully there is also a new release of `jaxb2_commons` to address this.

@soc we hope to get a new release soon (2.0.6) and then move to jakarta version

**Comment by mattrpav** [comment]
#389

**Comment by m2nhawk** [comment]
Any news on jaxb 3 Jakarta support for the JAXB Maven Plugin?

**Comment by mattrpav** [comment]
Planning to release shortly! Hopefully, within the next 5-10 days

**Comment by m2nhawk** [comment]
@mattrpav thank you for the very fast response and for your work!

**Comment by Lonzak** [comment]
>Planning to release shortly! Hopefully, within the next 5-10 days.
Thank you. I think we all can't wait to get v3.

Count-Down: 7 days to go.

**Comment by laurentschoelens** [comment]
We are doing one last major change on v3 with new namespace for plugins, with support of older and warning to move to newer.
Older namespace support will be dropped **after** v4-based plugin.
Once done, and tested, we'll be ready to GO 🚀

**Comment by laurentschoelens** [comment]
Hello everyone
Version 3.0.0 released (followed by 3.0.1 bugfix)
Working on 4.0 now
Enjoy

**Comment by Lonzak** [comment]
I tried the new plugin and it works nicely and the classes are generated. The only thing I didn't get working was the "toString" Plugin so I had to throw this out...

**Comment by laurentschoelens** [comment]
@Lonzak : could you share more context on this error of the `toString` plugin ?
If needed, you can create a question issue so we can help you with this 😄
