### ISSUE TITLE
JAXB AND XJC VERSIONS USED IN maven-jaxb2-plugin: 0.9.0 ?

### ISSUE THREAD

**Issue by ankit01122** [highsource/jaxb-tools#245]
JAXB AND XJC VERSIONS USED IN maven-jaxb2-plugin: 0.9.0 ? Because I cannot found those in release notes.

**Comment by laurentschoelens** [comment]
Hi @ankit01122 
0.9.0 uses the following (depending on plugin jaxb20 / jaxb21 / jaxb22)

		<jaxb20.version>2.0.5</jaxb20.version>
		<jaxb21.version>2.1.14</jaxb21.version>
		<jaxb22.version>2.2.7</jaxb22.version>

**Comment by laurentschoelens** [comment]
Closing w/ completed status since question answered
