### ISSUE TITLE
request file 

### ISSUE THREAD

**Issue by 09094080-Tao-Jiao** [highsource/jaxb-tools#248]
There is only file reponse  but no file request 
![图片](https://user-images.githubusercontent.com/7424315/175501068-35c03808-ef73-418f-b5a7-66e766ffe79d.png)

**Comment by laurentschoelens** [comment]
Hi @hachihub :
Could you please provide more context about this ?
The request you'd expect are well defined in your xsd ? Isn't file "CancelMessages" the class you're looking for (like the FailEoioMessage / FailEoioMessageResponse I see below) ?
Thanks in advanced for your reply

**Comment by laurentschoelens** [comment]
@09094080-Tao-Jiao any news on this ?
Without response, I'll close the issue as wontfix

**Comment by laurentschoelens** [comment]
Feel free to reopen if you have any problem
