### ISSUE TITLE
Generate classes with Jakarta namespace

### ISSUE THREAD

**Issue by joaomiguelsoares** [highsource/jaxb-tools#253]
Hi, how can i generate my classes with the "jakarta.*" namespace?

**Comment by laurentschoelens** [comment]
Just made a pull request to add jakarta jaxb support (jaxb3 / jaxb4)
https://github.com/highsource/maven-jaxb2-plugin/pull/255

**Comment by laurentschoelens** [comment]
Before official release of v3 plugin, you can use https://github.com/highsource/jaxb-tools/issues/233#issuecomment-1632508716

**Comment by laurentschoelens** [comment]
Linked to #199

**Comment by mattrpav** [comment]
#389
