### ISSUE TITLE
Merging maven-jaxb-plugin related repositories into this one

### ISSUE THREAD

**Issue by laurentschoelens** [highsource/jaxb-tools#264]
Issue to list actions done to migrate existing jaxb-tools related repositories into this one

**Comment by laurentschoelens** [comment]
First move all code into new directory:
```
mkdir maven-plugin
git mv CODE_OF_CONDUCT.md CONTRIBUTING.md LICENSE README.md build-1.8.bat build-10.bat dist full-build-1.8.bat full-build-10.bat full-build-9.bat plugin plugin-core pom.xml qrelease.bat samples src testing tests www maven-plugin/
git commit -m "mv from . to maven-plugin"
git push
```

**Comment by laurentschoelens** [comment]
Integrate jaxb-basics repository :
```
git remote add jaxb_basics https://github.com/highsource/jaxb2-basics.git
git fetch jaxb_basics --tags
git merge --allow-unrelated-histories jaxb_basics/master
```

Treat merge issues (.github folder and .gitignore file) and then commit merge
```
git add .github .gitignore
git commit
```

At this point, jaxb_basics is merged in `.` folder, now need to move it

```
mkdir basics 
git mv LICENSE README.md TODO.md ant basic deploy.bat dist full-build-9.bat plugins pom.xml qrelease.bat release.bat runtime samples testing tests tools  basics/
git commit -m "mv jaxb-basics code to basics"
git push
```

Repo merged 😄

**Comment by laurentschoelens** [comment]
Integrate jaxb-basics repository :
```
git remote add jaxb2-annotate-plugin https://github.com/highsource/jaxb2-annotate-plugin.git
git fetch jaxb2-annotate-plugin --tags
git merge --allow-unrelated-histories jaxb2-annotate-plugin/master
```

Treat merge issues (.github folder and .gitignore file) and then commit merge
```
git add .github .gitignore
git commit
```

At this point, jaxb2-annotate-plugin is merged in `.` folder, now need to move it

```
mkdir annotate 
git mv LICENSE README.md full-build-9.bat plugin pom.xml qrelease.bat samples tests annotate/
git commit -m "mv jaxb2-annotate-plugin code to annotate"
git push
```

Repo merged 😄

**Comment by thuri** [comment]
I had a look at the repository and i could try to create a complete maven reactor build for all the modules and submodules if you like and didn't start yet. I'd be happy to help so we can move forward with the jakarta migration. 
But i would need to rebase the repo before doing that which is bit of a pain because all the pom files changed :-(

**Comment by laurentschoelens** [comment]
Hi @thuri 
I've started with @mattrpav this task since migration to jakarta with interdependant projects (in different repos) will be a pain without breaking anything.
Active work on it so please be patient, it'll come soon

**Comment by thuri** [comment]
Yeah i've seen that both of you are active on this (Big Thank You by the way). Please tell me if I can be of any help. Otherwise I'll wait 

Am 17. Juni 2023 19:04:46 MESZ schrieb laurentschoelens ***@***.***>:

**Comment by hazendaz** [comment]
ok I opened similar ticket over on https://github.com/phax/maven-jaxb2-plugin/issues/13.  Its super confusing as to what is what.  I think the maven-jaxb2-plugin at phax is most up to date.  Need to pick up its logic for sure for jakartaEE.

**Comment by laurentschoelens** [comment]
@hazendaz : phax has been forked from this repo when this repo was searching for a new maintainer.
Since @mattrpav follow up on @highsource work, we'll try to make this repo evolve the best way we can with up-to-date technologies and jakarta version of this plugin :)

**Comment by laurentschoelens** [comment]
Missing hyperjaxb3 which will be done later. Opening new issue for this one and closing

**Comment by laurentschoelens** [comment]
Issue #317 created
