### ISSUE TITLE
Merge jaxb-annotate-plugin

### ISSUE THREAD

**Issue by mattrpav** [highsource/jaxb-tools#314]
git remote add jaxb2-annotate-plugin https://github.com/highsource/jaxb2-annotate-plugin.git
git fetch jaxb2-annotate-plugin --tags
git merge --allow-unrelated-histories jaxb2-annotate-plugin/master

Treat merge issues (.github folder and .gitignore file) and then commit merge

git add .github .gitignore
git commit

At this point, jaxb2-annotate-plugin is merged in . folder, now need to move it

mkdir annotate 
git mv LICENSE README.md full-build-9.bat plugin pom.xml qrelease.bat samples tests annotate/
git commit -m "mv jaxb2-annotate-plugin code to annotate"
git push

**Comment by laurentschoelens** [comment]
PR merged. Closing issue
