### ISSUE TITLE
Remove reresolution work around once jaxb-ri fixes regression

### ISSUE THREAD

**Issue by mattrpav** [highsource/jaxb-tools#338]
- [ ] Remove systemId reresolution work-around
- [ ] Detect minimum jaxb-ri version needed for fix in plugin
- [ ] Fail of jaxb version is less than required for the fix

ref: #329

**Comment by laurentschoelens** [comment]
Fix prepared for this one with tested https://github.com/eclipse-ee4j/jaxb-ri/pull/1767
