### ISSUE TITLE
Create a 'no-jaxb' mode of code generation

### ISSUE THREAD

**Issue by mattrpav** [highsource/jaxb-tools#340]
Use jaxb-maven-plugin to use xsd-driven creation of modules, but do not add or require any imports on jaxb (javax.xml, etc.

XSD is very effective at creating object models with extension and complex scenarios. However, not all users want to use XML as a format for those models.

This would allow users to create simple Java-only (no dependencies) POJOs for complex models without requiring JAXB or XML.

Also, we could optionally allow things like JPA (hyperjaxb) or JSON extensions to be added to the POJOs to create hybrid models that do not require JAXB API or JAXB runtime at all

**Comment by laurentschoelens** [comment]
Linked SO https://stackoverflow.com/questions/76095099/jaxb-xsd-xjb-to-pojo-without-annotations
