### ISSUE TITLE
Create xjc plugin to re-work collections-only xml wrapper tags

### ISSUE THREAD

**Issue by mattrpav** [highsource/jaxb-tools#341]
```
<items>
   <item id="1" ../>
   <item id="2" ../>
   <item id="3" ../>
</items>
```

Can be rendered into Java as:

```
Items items = new Items();
items.getItem() .. (collection of Item)
```

Instead we'd like to bypass the 'wrapper' object that is only a holder of collections.

```
List<Item> items = .. (w/ a collection type
```

**Comment by laurentschoelens** [comment]
Already started here by Alexey
https://github.com/highsource/jaxb-tools/tree/master/jaxb-plugins-parent%2Fjaxb-plugins%2Fsrc%2Fmain%2Fjava%2Forg%2Fjvnet%2Fjaxb%2Fplugin%2Felementwrapper

Need rework since failing on xjc generation if activated
