### ISSUE TITLE
[MAVEN_JAXB2_PLUGIN-53] Catalog with resolution by public id / namespace URI falls in Exception

### ISSUE THREAD

**Issue by highsource** [highsource/jaxb-tools#4]
https://java.net/jira/browse/MAVEN_JAXB2_PLUGIN-53

**Comment by laurentschoelens** [comment]
> https://java.net/jira/browse/MAVEN_JAXB2_PLUGIN-53
From web archive 

Hi,

I tried to make episode with a catalog resolution to work with maven has described in the page : http://jaxb.java.net/guide/Fixing_broken_references_in_schema.html in paragraph 1.2.1.2.

The xsd refers a public namespace with a defined schemalocation with the following data :
<xsd:import namespace="http://maven-jaxb2-plugin/samples/episode/a" schemaLocation="a.xsd"/>

The catalog defines the public namespace as :
PUBLIC "http://maven-jaxb2-plugin/samples/episode/a" "maven:org.jvnet.jaxb2.maven2:maven-jaxb2-plugin-sample-episode-a-maven!/a.xsd"

The given test case helps reproducing the problem that falls in an Exception during the generation of the classes.

For information, if I remove the tag schemaLocation="a.xsd", the generation works correctly. But I really wants to set the schemaLocation in the xsd file.

**Comment by laurentschoelens** [comment]
Cnico7 wrote
Hi,

I tried to make episode with a catalog resolution to work with maven has described in the page : http://jaxb.java.net/guide/Fixing_broken_references_in_schema.html in paragraph 1.2.1.2.

The xsd refers a public namespace with a defined schemalocation with the following data :
<xsd:import namespace="http://maven-jaxb2-plugin/samples/episode/a" schemaLocation="a.xsd"/>

The catalog defines the public namespace as :
PUBLIC "http://maven-jaxb2-plugin/samples/episode/a" "maven:org.jvnet.jaxb2.maven2:maven-jaxb2-plugin-sample-episode-a-maven!/a.xsd"

The given test case helps reproducing the problem that falls in an Exception during the generation of the classes.

For information, if I remove the tag schemaLocation="a.xsd", the generation works correctly. But I really wants to set the schemaLocation in the xsd file.

**Comment by laurentschoelens** [comment]
Lexi wrote
I've reproduced the problem, scheduling for 0.8.2.

**Comment by laurentschoelens** [comment]
Closed per https://github.com/highsource/jaxb-tools/issues/72
