### ISSUE TITLE
Align plugin namespaces with new package names

### ISSUE THREAD

**Issue by bschuhmann** [highsource/jaxb-tools#401]
🤔 wondering if it would make sense to also align plugins' namespaces to follow the refactoring from #378? The namespaces still all start with `http://jaxb2-commons.dev.java.net/basic/...` - have you thought about renaming them to something like `https://jaxb.jvnet.org/jaxb-plugins/...`?
The namespace for instance for the _Inheritance_ plugin would then change from `http://jaxb2-commons.dev.java.net/basic/inheritance` to `https://jaxb.jvnet.org/jaxb-plugins/inheritance`.
People need to migrate their Java code, so there shouldn't be a problem they also have to change their schemas - maybe allow both for some time? I was kind of expecting to do these changes after #378...

**Comment by mattrpav** [comment]
Yes, we’ve talked about it and I agree we should clean it up. 

I prefer urn syntax since the dns hostname doesn’t exist for jaxb.Janet.org. 

urn:jaxb.jvnet.org:plugin:foo
urn:jaxb.jvnet.org:plugin:bar

**Comment by mattrpav** [comment]
This is completed
