### ISSUE TITLE
Upgrade to jaxb 4.0.2

### ISSUE THREAD

**Issue by mattrpav** [highsource/jaxb-tools#410]

**Comment by cachescrubber** [comment]
Hi @mattrpav  - Sorry for piggy packing this issue, just a heads-up on a jaxb-ri issue which might affect this project in one way or another.

I (and others) have reported breaking changes in **jaxb-ri** between versions 4.0.2 and 4.0.3.

- https://github.com/eclipse-ee4j/jaxb-ri/issues/1742
- https://github.com/eclipse-ee4j/jaxb-ri/issues/1731
- https://github.com/eclipse-ee4j/jaxb-ri/issues/1724

The **jaxb-ri** maintainers are not very responsive when it comes to github issues apparently. So any expertise regarding this subject is greatly appreciated.
