### ISSUE TITLE
Upgrade to jaxb-ri 4.0.4

### ISSUE THREAD

**Issue by mattrpav** [highsource/jaxb-tools#425]
Note: jaxb-ri v4.0.3 has regressions

see: [#410]

**Comment by laurentschoelens** [comment]
This update will solve the following issues due to https://github.com/eclipse-ee4j/jaxb-ri/pull/1746 : 
- https://github.com/highsource/jaxb2-basics/issues/123
- https://github.com/highsource/jaxb2-annotate-plugin/issues/49

**Comment by laurentschoelens** [comment]
This update will need changes on if-exists fix due to https://github.com/eclipse-ee4j/jaxb-ri/pull/1745

**Comment by laurentschoelens** [comment]
This update will need work on https://github.com/highsource/jaxb-tools/issues/338 due to https://github.com/eclipse-ee4j/jaxb-ri/pull/1767
