### ISSUE TITLE
Invalid error message logged during execution

### ISSUE THREAD

**Issue by MarkARussell** [highsource/jaxb-tools#429]
The latest 3.0.1 version of the jaxb-maven-plugin logs an invalid/incorrect error message to the console during execution.  Specifically I see the message `[ERROR] Could not find JAXB 2.x API classes. Make sure JAXB 2.x API is on the classpath.`

It looks like maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJCMojo.java code still contains some string versions of the old javax.xml.bind packages which the code uses in an attempt to instantiate the classes.  The strings are used in the logApiConfiguration() function of the AbstractXJCMojo class.

The constants I think still needing updating:
* XML_SCHEMA_CLASS_QNAME
* XML_SCHEMA_RESOURCE_QNAME
* XML_ELEMENT_REF_CLASS_QNAME

The logApiConfiguration function may need some rework as well since it's attempting to resolve the JAXB version for logging purposes.

**Comment by mattrpav** [comment]
Holding off on releasing v4.0.0 until we look at this one. We might need a new v3.x as well

**Comment by laurentschoelens** [comment]
@mattrpav PR provided for master

**Comment by laurentschoelens** [comment]
Hi @MarkARussell 

@mattrpav just released v4 and available : https://central.sonatype.com/artifact/org.jvnet.jaxb/jaxb-maven-plugin/4.0.0

If you are not stuck with jaxb 3 api or jdk8 support, could you give it a try ?

V3.0.2 with backported fix will be available in a few days.

Thanks
Laurent

**Comment by MarkARussell** [comment]
Yep trialed the 4.0.0 version this morning and working perfectly.  Thanks for such a fast turn-around

**Comment by laurentschoelens** [comment]
> Yep trialed the 4.0.0 version this morning and working perfectly.  Thanks for such a fast turn-around

Many thanks to you for reporting this to us.
If you found other issues, feel free to open other issue here, we'll be glad to see what we could do to help 😀

**Comment by OLibutzki** [comment]
> V3.0.2 with backported fix will be available in a few days.

Do you still plan to release 3.0.2?

**Comment by laurentschoelens** [comment]
Yes but we need to work on multi release pipeline  
@mattrpav should be the most appropriate person to give an update on this one.
@OLibutzki : by curiosity, you need jakarta AND jdk8 ?

**Comment by OLibutzki** [comment]
> @OLibutzki : by curiosity, you need jakarta AND jdk8 ?

Unfortunately, yes... but I have to admit that this is certainly quite unusual.

**Comment by laurentschoelens** [comment]
Yes and jaxb3 is not quite supported too.
In any case, we'll do the 3.0.2 release too as planned 👍

**Comment by mattrpav** [comment]
JAXB 4 requires JDK 11.

ref: https://jakarta.ee/specifications/xml-binding/4.0/

**Comment by laurentschoelens** [comment]
> Yes and jaxb3 is not quite supported too. In any case, we'll do the 3.0.2 release too as planned 👍 But with not as many bugfixes as in 4.0.1 or 2.0.10

@OLibutzki : 3.0.2 has been released (sorry for the delay 😄), enjoy !

**Comment by OLibutzki** [comment]
Thanks, I've been waiting every day. :wink:
