### ISSUE TITLE
SimpleToString plugin exists, but cannot be activated/used?

### ISSUE THREAD

**Issue by soc** [highsource/jaxb-tools#432]
It seems the code is [here](https://github.com/highsource/jaxb-tools/blob/master/jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/simpletostring/SimpleToStringPlugin.java), but specifying `<arg>-XsimpleToString</arg>` reports:

> unrecognized parameter -XsimpleToString

Is this intentional?

**Comment by laurentschoelens** [comment]
Hi @soc 

Did you add jaxb2-basics (or the new name, depending which version of the plugin you use) in jaxb-maven-plugin configuration ?

The jar containing the XJC plugins is splitted from the one containing the maven-plugin itself.

Laurent

**Comment by soc** [comment]
@laurentschoelens Yes. All other plugins work fine, even the related ones like `simpleEquals` and `simpleHashCode`.

I had a short look at the code if there was a hint it was disabled, but didn't see anything, therefore my question.

**Comment by laurentschoelens** [comment]
From what I've seen the plugin had never been declared in the https://github.com/highsource/jaxb-tools/blob/master/jaxb-plugins-parent/jaxb-plugins/src/main/resources/META-INF/services/com.sun.tools.xjc.Plugin file where it is clearly missing, and from initial repo too 🤔

I'd suggest not using it for the moment and if this plugin is viable, we'll add it to the list

**Comment by laurentschoelens** [comment]
Alexey was adding the 3 "simple" / reflection free plugins (equals / hashCode / toString) but he ended up removing Simpletostring from the file mentionned above.
The plugin wasnt even mentionned in previous repo...

So I would say, yes it's intentionnal not to be activated.
The other question is : can we add it as new plugin in it's actual state ? I don't know... Let us see first what it does 😀

**Comment by soc** [comment]
@laurentschoelens I was interested in the `equals`/`hashCode`/toString` situation anyway, wondering if it might make sense to use more "modern Java" to reduce the amount of generated code and make those methods basically behave like `equals`/`hashCode`/toString` on records. (Though inheritance will be a problem.)

**Comment by mattrpav** [comment]
@laurentschoelens we take an approach of copying the locator along side the generated classes to give a runtime dependency-free solution for the boiler plate toString. 

I think we could copy in the locator strategy class just like ObjectFactory and package-info. 

I think runtime Dependency-free approach should be the default at some point as well.

**Comment by laurentschoelens** [comment]
> @laurentschoelens we take an approach of copying the locator along side the generated classes to give a runtime dependency-free solution for the boiler plate toString. 
> 
> I think we could copy in the locator strategy class just like ObjectFactory and package-info. 
> 
> I think runtime Dependency-free approach should be the default at some point as well. 

My guess is we first need to look at existing but not active plugin to see what had been done by Alexey and then make it works or start from something new for this simpleToString xjc plugin.

**Comment by soc** [comment]
Ok, thanks that answers my questions!

**Comment by laurentschoelens** [comment]
From what I've seen, the SimpleToString plugin is just a copy of the ToString plugin, so it depend on jaxb-plugins-runtime...
Not very useful for the moment

**Comment by laurentschoelens** [comment]
@soc new issue follow up of yours https://github.com/highsource/jaxb-tools/issues/433
