### ISSUE TITLE
jaxb-tools vs hisrc-basicjaxb (org.patrodyne.jvnet)

### ISSUE THREAD

**Issue by mrpiggi** [highsource/jaxb-tools#450]
I have already asked the question on [SO](https://stackoverflow.com/questions/77254281), but unfortunately did not received an answer. That's why I'm trying my luck here.

Besides your project there is also [hisrc-basicjaxb](https://github.com/patrodyne/hisrc-basicjaxb). Are you aware of this? Would it possibly make sense to join forces and merge the two projects back into one, or to endeavor to work together?  It would be a real shame if resources were wasted and two projects with the same goal ended up existing in parallel.

**Comment by mrpiggi** [comment]
https://github.com/patrodyne/hisrc-basicjaxb/issues/14

**Comment by laurentschoelens** [comment]
Hi @mrpiggi 
Sorry I'm not watching SO (maybe I should check sometimes on questions regarding this plugin now)

I've seen what has been done and I'm already in contact with phax (which you named Philip Helger) and he's looking at our recent work.
I'm not aware of what has been done under patrodyne and don't know him neither.

Our goal with Matt was (and still is) to maintain the original repository (in fact repositories but we did merge the related jaxb-tools into this one), which both projects you mention are forked from.
We're not closed to any PR from anyone. It'd be easier to maintain only one repo, and since now we have active dev here, maybe it'd be a good start, but I don't want to force anyone to choose one repository or another : everyone's work is valuable and what phax and patrodyne did helped people when Alexey passed away (sadly)

**Comment by laurentschoelens** [comment]
Related issue https://github.com/phax/maven-jaxb2-plugin/issues/13

**Comment by mattrpav** [comment]
@laurentschoelens comment captured my thoughts as well. Anyone is welcome to participate or use whichever implementation they wish. A great part of open source is that there can be options!

**Comment by mrpiggi** [comment]
@patrodyne has replied and unfortunately intends not to collaborate but to work in parallel. At least that has now been clarified.

**Comment by laurentschoelens** [comment]
Seen the answer.

I'm waiting for phax review of current state of the jaxb-tools repository (he'll do it when having some time to proceed)

**Comment by laurentschoelens** [comment]
I've also taken some time to go to SO to look at some issue. Feel free to update your question there 😉

**Comment by laurentschoelens** [comment]
@mrpiggi : updated answer on SO and also here too :

With @phax's final review on current state of the plugin, he decided to archive is own repository and to use `highsouce/jaxb-tools`

Added corresponding section to the [migration guide - Migration from `phax/maven-jaxb2-plugin`](https://github.com/highsource/jaxb-tools/wiki/JAXB-Tools-Migration-Guide#phax)

**Comment by mrpiggi** [comment]
@laurentschoelens Many thanks for the update. Currently , I am still using [patrodyne/hisrc-basicjaxb](https://github.com/patrodyne/hisrc-basicjaxb/) but as I want to update from Java 17 to Java 21 in the near future, I will have a look to migrate (back) to `jaxb-tools`.

If there are any problems, I will reach back to you. I will try to document the migration process in order to provide a migration guide like you did for [phax/maven-jaxb2-plugin/](https://github.com/phax/maven-jaxb2-plugin/)

**Comment by laurentschoelens** [comment]
You're welcome @mrpiggi 😉 
It's not mentionned (yet) but our build is running also with JDK21 in the github workflow so it's tested with JDK21 too 😄

**Comment by laurentschoelens** [comment]
> @laurentschoelens Many thanks for the update. Currently , I am still using [patrodyne/hisrc-basicjaxb](https://github.com/patrodyne/hisrc-basicjaxb/) but as I want to update from Java 17 to Java 21 in the near future, I will have a look to migrate (back) to `jaxb-tools`.
> 
> If there are any problems, I will reach back to you. I will try to document the migration process in order to provide a migration guide like you did for [phax/maven-jaxb2-plugin/](https://github.com/phax/maven-jaxb2-plugin/)

Hi @mrpiggi, did you use jaxb-tools in the end ?

**Comment by mrpiggi** [comment]
Not yet, still waiting for #433 as I am rather reluctant to additional runtime dependencies and want the generated classes to differ least possible.

**Comment by laurentschoelens** [comment]
> Not yet, still waiting for #433 as I am rather reluctant to additional runtime dependencies and want the generated classes to differ least possible.

I'll try to work on this now since we got 2.x and 3.x finally out 😄

**Comment by mrpiggi** [comment]
> I'll try to work on this now since we got 2.x and 3.x finally out 😄

Great to hear although migration is currently no urgent task for me. So, you don't have to hurry, at least from my side ;)
