### ISSUE TITLE
Update docs for change of artifact name from `jaxb2-basics` to `jaxb-plugins`

### ISSUE THREAD

**Issue by bixycler** [highsource/jaxb-tools#452]
In issue #375, many codes were updated to change from `jaxb2-basics` to `jaxb-plugins`, but the docs and wiki are left out-of-date. Now we should reflect that change into the docs.

**Comment by laurentschoelens** [comment]
Updated wiki pages :
* https://github.com/highsource/jaxb-tools/wiki/JAXB2-Basic
* https://github.com/highsource/jaxb-tools/wiki/Using-JAXB2-Basics-Plugins
* https://github.com/highsource/jaxb-tools/wiki/JAXB2-HashCode-Plugin
* https://github.com/highsource/jaxb-tools/wiki/JAXB2-Equals-Plugin
* https://github.com/highsource/jaxb-tools/wiki/JAXB2-ToString-Plugin
* https://github.com/highsource/jaxb-tools/wiki/JAXB2-Copyable-Plugin
* https://github.com/highsource/jaxb-tools/wiki/JAXB2-Mergeable-Plugin
* https://github.com/highsource/jaxb-tools/wiki/JAXB2-Namespace-Prefix-Plugin
* https://github.com/highsource/jaxb-tools/wiki/Using-JAXB-Plugins

@bixycler : could you check if you see more to change or if changes are not clear enough ?

**Comment by laurentschoelens** [comment]
Thanks for your help in this @bixycler and making the wiki pages better 😄
