### ISSUE TITLE
CamelCase Always plugin (and other org.andromda.thirdparty.jaxb2_commons plugins)

### ISSUE THREAD

**Issue by rbertucat** [highsource/jaxb-tools#460]
I'm trying to migrate from jaxb2 to jaxb4. The CamelCase Always plugin used to work pretty well.

Now in jaxb4, `com.sun.xml.bind.api.impl.NameConverter` has been updated to `org.glassfish.jaxb.core.api.impl.NameConverter` so the plugin fails.

Any chance you could suggest a workaround - a plugin doing the same end result? Or do you plan to update the CamelCase Always plugin?

Example:
```XML
<plugin>
    <groupId>org.jvnet.jaxb2.maven2</groupId>
    <artifactId>maven-jaxb2-plugin</artifactId>
    <version>0.8.0</version>
    <executions>
        <execution>
            <id>jaxb-generate</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <generatePackage>YOUR.PACKAGE.HERE</generatePackage>
        <args>
            <arg>-camelcase-always</arg>
        </args>
        <bindingDirectory>src/main/binding</bindingDirectory>
        <schemas>
            <schema>
                <url>http://YOUR.XSD.HERE</url>
            </schema>
        </schemas>
        <extension>true</extension>
        <plugins>
            <plugin>
                <groupId>org.andromda.thirdparty.jaxb2_commons</groupId>
                <artifactId>camelcase-always</artifactId>
                <version>1.0</version>
            </plugin>
        </plugins>
    </configuration>
</plugin>
```
From: https://stackoverflow.com/questions/8916398/how-can-i-get-jaxb2-to-emit-camelcase-bindings
Sources are here: https://repo1.maven.org/maven2/org/andromda/thirdparty/jaxb2_commons/camelcase-always/1.0/

**Comment by laurentschoelens** [comment]
I look to get source code of this plugin (and others ones if interesting). Maybe we could get this in 4.0.1 which is in staging mode

**Comment by laurentschoelens** [comment]
PR provided for camelcase : need to update wiki now :)

**Comment by laurentschoelens** [comment]
Need first to get it pass the build workflow 😂
Then @mattrpav will take a look and merge it since I provide the PR
Next release (v4.0.1) will be planned for before Christmas 🎁

**Comment by laurentschoelens** [comment]
Here is the wiki's documentation and how-to use CamelCase plugin from jaxb-tools : https://github.com/highsource/jaxb-tools/wiki/JAXB-CamelCase-Plugin
I've also added extra documentation for the other 4 plugins that were imported from the `andromda` groupId.

**Comment by laurentschoelens** [comment]
@rbertucat : this is now merged in master (4.0.1) so be part of the next release by the end of the month.

**Comment by rbertucat** [comment]
@laurentschoelens we were able to test on our side and it works great! Thank you so much for the quick turnaround!

**Comment by rbertucat** [comment]
@laurentschoelens any update on the 4.0.1 release date please?

**Comment by laurentschoelens** [comment]
@mattrpav ?
If all green this week

**Comment by laurentschoelens** [comment]
@rbertucat : sorry for the delay but good news, 4.0.2 version has been released. Enjoy

**Comment by rbertucat** [comment]
@laurentschoelens thanks for the release. We've been able to switch to 4.0.3, and we are also using the `jaxb-maven-plugin` directly now. It's working great.

**Comment by laurentschoelens** [comment]
Thanks for the feedback @rbertucat 😄
