### ISSUE TITLE
Migrating from JAXB 2 to 4, can no longer find -Xlocator

### ISSUE THREAD

**Issue by FranklinChen** [highsource/jaxb-tools#470]
I searched the Internet for information about how to keep my -Xlocator configuration from JAXB 2 code generation from XML Schema. I used to get the following generated, but can't figure out how to do it with JAXB 4.

```
import com.sun.xml.bind.Locatable;
import com.sun.xml.bind.annotation.XmlLocation;
import org.xml.sax.Locator;
```

and for each class

```
public class ... implements Locatable {
    @XmlLocation
    @XmlTransient
    protected Locator locator;

    public Locator sourceLocation() {
        return locator;
    }

    public void setSourceLocation(Locator newLocator) {
        locator = newLocator;
    }
}
```

**Comment by laurentschoelens** [comment]
Could you tell us which plugin activates this ?

**Comment by laurentschoelens** [comment]
The option seems to exists still

Here [link](https://eclipse-ee4j.github.io/jaxb-ri/4.0.3/docs/ch04.html#d0e3673) to documentation

> -Xlocator           :  enable source location support for generated code

**Comment by FranklinChen** [comment]
I just noticed that I mis-configured my pom.xml. Sorry! All is good.

**Comment by laurentschoelens** [comment]
Hope everything was fine in plugin migration
