### ISSUE TITLE
Enum of int values

### ISSUE THREAD

**Issue by sameersapra-manulife** [highsource/jaxb-tools#474]
Using below dependency and spring boot parent 3.2.1,  it does not create Enum class with int type values.  As soon as i change it to string type and values then it generates the enum class.

<dependency>
    <groupId>org.jvnet.jaxb</groupId>
    <artifactId>jaxb-maven-plugin</artifactId>
    <version>3.0.1</version>
</dependency>

	<xsd:simpleType name="BooleanEnum">
		<xsd:annotation>
			<xsd:appinfo>
				<jaxb:typesafeEnumClass/>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:restriction base="xsd:int">
			<xsd:enumeration value="0">
				<xsd:annotation>
					<xsd:documentation>False.</xsd:documentation>
					<xsd:appinfo>
						<jaxb:typesafeEnumMember name="False"/>
					</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="1">
				<xsd:annotation>
					<xsd:documentation>True.</xsd:documentation>
					<xsd:appinfo>
						<jaxb:typesafeEnumMember name="True"/>
					</xsd:appinfo>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

**Comment by laurentschoelens** [comment]
Hello @sameersapra-manulife 

Did you try the v4 of the plugin which is based on jaxb 4 and jdk11 baseline ?
I'll try to investigate

**Comment by laurentschoelens** [comment]
@sameersapra-manulife 

Using the following XSD with latest version of jaxb-maven-plugin (testing against 3.0.1, 4.0.0 and current 4.0.1-SNAPSHOT), I get the following result for the `BooleanEnum` type :

```xml
<?xml version='1.0'?>
<xsd:schema targetNamespace="http://www.example.org"
            xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb" jaxb:version="3.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:simpleType name="BooleanEnum">
    <xsd:annotation>
      <xsd:appinfo>
        <jaxb:typesafeEnumClass/>
      </xsd:appinfo>
    </xsd:annotation>
    <xsd:restriction base="xsd:int">
      <xsd:enumeration value="0">
        <xsd:annotation>
          <xsd:documentation>False.</xsd:documentation>
          <xsd:appinfo>
            <jaxb:typesafeEnumMember name="False"/>
          </xsd:appinfo>
        </xsd:annotation>
      </xsd:enumeration>
      <xsd:enumeration value="1">
        <xsd:annotation>
          <xsd:documentation>True.</xsd:documentation>
          <xsd:appinfo>
            <jaxb:typesafeEnumMember name="True"/>
          </xsd:appinfo>
        </xsd:annotation>
      </xsd:enumeration>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>
```

```java
@XmlType(name = "BooleanEnum", namespace = "http://www.example.org")
@XmlEnum(Integer.class)
public enum BooleanEnum {


    /**
     * False.
     * 
     */
    @XmlEnumValue("0")
    False(0),

    /**
     * True.
     * 
     */
    @XmlEnumValue("1")
    True(1);
    private final int value;

    BooleanEnum(int v) {
        value = v;
    }

// Eluded end of class content
}
```

For me, the result is what you'd expect : java enum class with integer-type value.

**Comment by sameersapra-manulife** [comment]
Thank you for providing a working example.  But, it turned to be an issue on my side.
