### ISSUE TITLE
customize toString() on enums

### ISSUE THREAD

**Issue by Rizen59** [highsource/jaxb-tools#520]
Hi,

With the ToString plugin, classes implements ToString but not enums.
With the EnumValue plugin, enums can EnumValue.

Maybe I didn't find how to do, but is it possible to customize the toString method of enums? For exemple to use a resourceBundle.

Best regards,

**Comment by laurentschoelens** [comment]
Hi @Rizen59 
You can follow the wiki page of the [toString plugin](https://github.com/highsource/jaxb-tools/wiki/JAXB2-ToString-Plugin)

You can extends the default strategy with custom implementation for EnumValue with the `-XtoString-toStringStrategyClass=com.acme.foo.MyToStringStrategy` argument

**Comment by laurentschoelens** [comment]
Or maybe I misunderstood your problem. Could you provide a MRE ?
You said that the `toString` plugin was not applied to Enum generated with `EnumValue` plugin, is that right ?

**Comment by Rizen59** [comment]
Hi Laurent,

Firstly thanks for your quick answer!
I pushed a sample to demonstrate the situation here: https://github.com/Rizen59/jaxb-tostring

If you generate the model you'll see that objects Console / Consoles / Devices implements ToString and override the methods to use the strategy I defined. But not Model and Vendor.

What I tried to do was override the toString also in enums, to be able to use the resource bundles into (provided also in the sample project).

Also I was wondering something : 

- with `mvn jaxb:generate` the model is generated but the objects does not implement ToString
- with `mvn install` it is

Is it normal?

**Comment by laurentschoelens** [comment]
Thanks for the example. I'll take a look soon.

For the other question, it depends of your build config but it's normal mvn behavor. See [comment here](https://github.com/highsource/jaxb-tools/issues/449#issuecomment-1802230408)

**Comment by Rizen59** [comment]
Thanks for your feedback.
Maybe I'm not familiar enough with the maven build process but it would be convenient that the model generation apply also the jaxb-plugins. I will not check that for the moment, it was just an observation.

About the toString an enum I found an old issue with the same question: https://github.com/highsource/jaxb2-basics/issues/31
At that time the response was to not add a ToString on enums but manage it directly in the strategy.
But how the strategy could be called if the enum does not implement it?

**Comment by laurentschoelens** [comment]
For the `toString` question, the original answer was to add the following method in your custom strategy :

```java
public StringBuilder append(ObjectLocator locator,
                                StringBuilder buffer,
                                Object value) {

        if (value instanceof EnumValue<?>) {
            // do your stuff here of calling the resource bundle to get actual wanted displayed value
            return super.append(locator, buffer,
                    ((EnumValue<?>) value).enumValue());
        } else {
            return super.append(locator, buffer, value);
        }
    }
```

This only works if you don't call the `toString` on the `enum` class but on the model object (like in the `Console` object, it'll be called in the following block generated by the `-XtoString` plugin) :

```java
        {
            Model theModel;
            theModel = this.getModel();
            strategy.appendField(locator, this, "model", buffer, theModel, (this.model!= null));
        }
```

Will it be enough for your use case ?

**Comment by Rizen59** [comment]
No really because I wanted to call toString directly from the enum :/

Thanks your previous answer on the configuration!

**Comment by laurentschoelens** [comment]
OK so my guess is to take back original PR submission in 2015 and adapt it to jaxb-tools latest version

I'll push a PR according to this.

**Comment by Rizen59** [comment]
I tested the PR and it works like a charm!

Just notice all tests didn't pass on my computer. But that's something I have on master also.
Do you want I add a new issue about this? I checked on Windows 10 with JDK 21.

> [INFO] Running org.jvnet.jaxb.maven.util.tests.CollectionsUtilsTests
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s -- in org.jvnet.jaxb.maven.util.tests.CollectionsUtilsTests
> [INFO]
> [INFO] Results:
> [INFO]
> [ERROR] Failures:
> [ERROR]   IOUtilsTests.reorderFilesIncludesWithWildcardFirst:76 expected:<[common/c1].xsd> but was:<[a].xsd>
> [ERROR]   IOUtilsTests.reorderFilesIncludesWithWildcardMiddle:99 expected:<[common/c1].xsd> but was:<[b].xsd>
> [INFO]
> [ERROR] Tests run: 14, Failures: 2, Errors: 0, Skipped: 0

**Comment by laurentschoelens** [comment]
Yes please, it's a problem from `File.separatorChar` not being used in the test itself

**Comment by Rizen59** [comment]
Hi Laurent,

Not a problem, it's done here: https://github.com/highsource/jaxb-tools/issues/522
