### ISSUE TITLE
Switch to javaparser 3.x

### ISSUE THREAD

**Issue by winfriedgerlach** [highsource/jaxb-tools#529]
This project uses `com.google.code.javaparser:javaparser:1.0.11`. This release is now 10 years old (02/2014) and the project is meanwhile dead and replaced by a fork, https://github.com/javaparser/javaparser

Also, the old library used has LGPL license only while the fork is available under both LGPL and Apache license, which may better suit commercial users.

It would be great if you could make the switch to `com.github.javaparser:javaparser-core:3.x.x`.

**Comment by laurentschoelens** [comment]
Hi @winfriedgerlach :
I've already tried to move to `javaparser` 3.x but it was a bit complicated from that time.
I'll try to give a look at this now that everything as been merged here

**Comment by laurentschoelens** [comment]
If also you want, you can also provide PR 😄

**Comment by winfriedgerlach** [comment]
@laurentschoelens I did start a PR but noticed quickly the same as you: Some changes are not trivial and unfortunately if have zero prior knowledge regarding javaparser, so it's quite likely I would break something...

**Comment by laurentschoelens** [comment]
No problem, I'll give it a look after next 4.x release 😉

**Comment by winfriedgerlach** [comment]
@laurentschoelens If that works for you, great! I like incremental, smaller updates.

**Comment by laurentschoelens** [comment]
Note on upgrading to v3 : https://javaparser.org/2-5-1-to-3-0-0-migration-guide/

**Comment by laurentschoelens** [comment]
Created : https://github.com/highsource/jaxb-tools/pull/530

**Comment by laurentschoelens** [comment]
Move to javaparser 3 is locked by https://github.com/javaparser/javaparser/issues/4355

**Comment by laurentschoelens** [comment]
@winfriedgerlach : managed to fix the v3.x migration blocking error. Build is OK with 3.0.1. Will try to move to latest 3.x now

**Comment by winfriedgerlach** [comment]
@laurentschoelens wow, great progress! Thanks again for your effort!
