### ISSUE TITLE
Support JPMS?

### ISSUE THREAD

**Issue by onacit** [highsource/jaxb-tools#533]
Can we have your support for the JPMS?

* Add `module-info.java`
* Or put an [`Automatic-Module-Name`](http://branchandbound.net/blog/java/2017/12/automatic-module-name/)

Thank you.

**Comment by laurentschoelens** [comment]
Thanks for sharing the link. You need it on the "runtime" dependency only ?

**Comment by onacit** [comment]
@laurentschoelens No, sir. The module info is also required in build time.

```
[ERROR]   (package org.jvnet.jaxb.lang is declared in the unnamed module, but module com.github.jinahya.spdx.license.list does not read it)
```

**Comment by laurentschoelens** [comment]
That's not what I meant sorry. The runtime dependency is `jaxb-plugins-runtime`'s artifact one 😄

**Comment by onacit** [comment]
@laurentschoelens Yes it is, I think, sir.

**Comment by laurentschoelens** [comment]
PR #534 created 😉
