### ISSUE TITLE
JAXB Maven Plugin: locale is ignored?

### ISSUE THREAD

**Issue by ggiambo** [highsource/jaxb-tools#538]
I'm trying to generate Java classes starting from an XSD.
The XSD contains documentation in multiple languages:

```xsd
<xs:annotation>
    <xs:documentation xml:lang="de">DE: person description</xs:documentation>
    <xs:documentation xml:lang="en">EN: person description</xs:documentation>
    <xs:documentation xml:lang="fr">FR: person description</xs:documentation>
    <xs:documentation xml:lang="it">IT: person description</xs:documentation>
</xs:annotation>
```

In the `pom.xml` I defined the locale to be german:

```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.jvnet.jaxb</groupId>
                <artifactId>jaxb-maven-plugin</artifactId>
                <version>4.0.3</version>
...
                <configuration>
                    <locale>de</locale>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

The documentation in the generated Java classes is set to italian, the last entry of  `<xs:documentation>`.
```java
public class Person {

    /**
     * IT: name description
     * 
     */
    @XmlElement(required = true)
    protected String name;
```

An example micro-project can be found [here](https://github.com/ggiambo/JaxbTesting)

**Comment by laurentschoelens** [comment]
Hi @ggiambo 
Thanks for creating this issue.
I guess plugin is not adapted (yet) to language selection based on multiple XSD documentation.

Since you created a sample project, we'll try to see if it's easily fixable 😄

**Comment by laurentschoelens** [comment]
This should be addressed in XJC (in [eclipse-ee4j/jaxb-ri](https://github.com/eclipse-ee4j/jaxb-ri)) since javadoc parsing and generation has been implemented there without the need of a plugin

**Comment by laurentschoelens** [comment]
Closing in favor of https://github.com/eclipse-ee4j/jaxb-ri/issues/1801
