### ISSUE TITLE
Needs update to latest commons-lang3 & commons-text

### ISSUE THREAD

**Issue by davija** [highsource/jaxb-tools#540]
Version 4.0.6 of jaxb-maven-plugin & jaxb-plugin-annotate rely on a method that has been deprecated and running with any version later 3.12.0 breaks.

This is in:
org.apache.commons.text.translate.NumericEntityEscaper.between (NumericEntityEscaper.java:59)
![image](https://github.com/highsource/jaxb-tools/assets/138913/a2aef752-d057-495b-884b-46a679901434)

Please update to use the latest commons-lang3 & commons-text libraries.

**Comment by davija** [comment]
Digging through the code it appears this is related to usage of StringEscapeUtils from org.apache.commons.text.StringEscapeUtils

**Comment by mattrpav** [comment]
Our usage of commons-* is pretty minimal. We may look to remove it altogether and either use more modern JDK built-in functions or self-host a few of the utilities that are used.

**Comment by davija** [comment]
That would be nice, but in the mean time we need something that works with newer versions as we have dependencies which require newer versions.  When we use the newer versions, this plugin pukes.

**Comment by laurentschoelens** [comment]
@davija thanks for the report
@mattrpav : outside of plugin's usage, it would be nice to drop some dependencies but here I guess the use-case is using `org.jvnet.jaxb.plugin.commons_lang.XjcCommonsLangPlugin` which depends on commons-lang itself 😄

**Comment by laurentschoelens** [comment]
The #542 PR fixes the issue here by removing the unwanted / conflicted dependencies.

**Comment by laurentschoelens** [comment]
@davija feel free to look at the PR

**Comment by davija** [comment]
@laurentschoelens I looked at it this morning and it should resolve my issue so I closed my PR in favor of this one.

**Comment by laurentschoelens** [comment]
@davija 4.0.7 just been released and should be available in maven central soon

**Comment by laurentschoelens** [comment]
You can also go for 4.0.8 which includes another fix (for another unrelated issue)

Regards
