### ISSUE TITLE
jaxb-plugins-runtime et al  - wrong 'Require-Capability' MANIFEST entry

### ISSUE THREAD

**Issue by lichtin** [highsource/jaxb-tools#548]
jaxb-plugins-runtime et al  - wrong 'Require-Capability' MANIFEST entry

(e.g. for version 4.0.6):

Require-Capability: osgi.ee;filter:="(osgi.ee=UNKNOWN)"

It looks like the version of the "maven-bundle-plugin" in use to build the JARs is too old, it doesn't generate proper MANIFEST entry.

**Comment by laurentschoelens** [comment]
Hi @lichtin 

Thanks for the report

Using newer version (5.1.9) leads to :
```
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=11))"
```

Does that seems OK for you ?

**Comment by lichtin** [comment]
perfect

**Comment by laurentschoelens** [comment]
PR done 😄

**Comment by laurentschoelens** [comment]
Hi @lichtin 

4.0.8 version has been released. You can safely go for it to have the fix for your issue.

Thanks again to have seen this.

It'll be backported to v2 soon too
