### ISSUE TITLE
Failed to parse plugin descriptor for org.jvnet.jaxb:jaxb-plugins:X.X.X

### ISSUE THREAD

**Issue by oliverunger** [highsource/jaxb-tools#555]
No plugin descriptor found at META-INF/maven/plugin.xml
In the jar in m2 in folder maven is only another folder org.jvnet.jaxb
Tested several versions 3.0.1, 4.0.0 and 4.0.1

**Comment by laurentschoelens** [comment]
Hi @oliverunger 

What are you searching for ? 
I'm pretty sure this artifact is for xjc plugins and not the maven plugin itself

Thanks for your reply

Laurent

**Comment by laurentschoelens** [comment]
Could you tell us what was the problem and what solution you found to solve it please ? It may help others users facing your issue.

Thanks
