### ISSUE TITLE
org.jvnet.jaxb:jaxb2-basics-runtime:jar:2.0.12 references missing org.jvnet.jaxb2_commons:jaxb2-basics-runtime:2.0.12

### ISSUE THREAD

**Issue by sepe81** [highsource/jaxb-tools#557]
After updating from 2.0.9 to 2.0.12 there is a missing transitive dependency, referencing the "old" groupId org.jvnet.jaxb2_commons

compare
https://repo1.maven.org/maven2/org/jvnet/jaxb/jaxb2-basics-runtime/2.0.9/jaxb2-basics-runtime-2.0.9.pom
with
https://repo1.maven.org/maven2/org/jvnet/jaxb/jaxb2-basics-runtime/2.0.12/jaxb2-basics-runtime-2.0.12.pom

2.0.9 contains:
```
<dependency>
  <groupId>org.glassfish.jaxb</groupId>
  <artifactId>jaxb-core</artifactId>
  <scope>provided</scope>
</dependency>
```

2.0.12 contains:
```
<dependency>
  <groupId>org.jvnet.jaxb2_commons</groupId>
  <artifactId>jaxb2-basics-runtime</artifactId>
  <version>2.0.12</version>
</dependency>
```

@mattrpav Could this be corrected in a new maintenance release, or am I mistaken?

**Comment by laurentschoelens** [comment]
Hi @sepe81

Same problem for me and same analysis as you.
We'll see if we can upload the missing 2.0.12 with old groupId but we'll need a new 2.0.13 to fix another issue (the release process override the range version set to fix https://github.com/highsource/jaxb-tools/issues/465)

**Comment by laurentschoelens** [comment]
Hi @sepe81 

Could you check back : the artifact got uploaded in maven central

https://repo1.maven.org/maven2/org/jvnet/jaxb2_commons/jaxb2-basics-runtime/2.0.12/

Thanks

**Comment by laurentschoelens** [comment]
Tested OK on own project

**Comment by sepe81** [comment]
Hi @laurentschoelens – thanks a lot, now it gets resolved:

[INFO] +- org.jvnet.jaxb:jaxb2-basics-runtime:jar:2.0.12:compile
[INFO] |  \- org.jvnet.jaxb2_commons:jaxb2-basics-runtime:jar:2.0.12:compile
