### ISSUE TITLE
ToStringStrategy not found in v4?

### ISSUE THREAD

**Issue by membersound** [highsource/jaxb-tools#559]
I migrated from javax to jakarta.
Now the package `org.jvnet.jaxb.lang.*` cannot be found anymore (eg `import org.jvnet.jaxb.lang.JAXBToStringStrategy`), but I'd like to use the `-Xtostring` option.

Is this a bug, or is there something wrong with my config?
Of course I followed the migration guide and https://github.com/highsource/jaxb-tools/wiki/Using-JAXB2-Basics-Plugins, and I cannot see anything missing here.

```
<project>
    <dependencies>
        <dependency>
            <groupId>org.jvnet.jaxb</groupId>
            <artifactId>jaxb-plugins</artifactId>
            <version>4.0.8</version>
        </dependency>
        <dependency>
            <groupId>org.jvnet.jaxb</groupId>
            <artifactId>jaxb-plugins-runtime</artifactId>
            <version>4.0.8</version>
        </dependency>
        <dependency>
            <groupId>org.jvnet.jaxb</groupId>
            <artifactId>jaxb-plugin-annotate</artifactId>
            <version>4.0.8</version>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>4.0.8</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>4.0.2</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>xsd2java</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jvnet.jaxb</groupId>
                        <artifactId>jaxb-maven-plugin</artifactId>
                        <version>4.0.8</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                                <configuration>
                                    <markGenerated>true</markGenerated>
                                    <noFileHeader>true</noFileHeader>
                                </configuration>
                            </execution>
                        </executions>
                        <configuration>
                            <extension>true</extension>
                            <args>
                                <arg>-XtoString</arg>
                            </args>
                            <plugins>
                                <plugin>
                                    <groupId>org.jvnet.jaxb</groupId>
                                    <artifactId>jaxb-plugins</artifactId>
                                    <version>4.0.8</version>
                                </plugin>
                            </plugins>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
```
[jaxb-example.zip](https://github.com/user-attachments/files/16598213/jaxb-example.zip)

**Comment by laurentschoelens** [comment]
Hi @membersound 

What kind of error did you get ?

I'd suggest some changes in your `pom.xml`: the following should be removed in the `dependencies` section, you only need `jaxb-plugins-runtime` as project's dependency :

```xml
        <dependency>
            <groupId>org.jvnet.jaxb</groupId>
            <artifactId>jaxb-plugins</artifactId>
            <version>4.0.8</version>
        </dependency>
        <dependency>
            <groupId>org.jvnet.jaxb</groupId>
            <artifactId>jaxb-plugin-annotate</artifactId>
            <version>4.0.8</version>
        </dependency>
```

I'd also make all configuration goes into the same `configuration` tag.

**Comment by membersound** [comment]
Stripping the dependencies did not change anything.
The main problem is that the generated java class `implements org.jvnet.jaxb.lang.ToString`, which is the source for the old jaxb2 ToString plugin. Even though I'm not referencing it anymore.

So, on the generated class, the following imports are wrong:

```
import org.jvnet.jaxb.lang.JAXBToStringStrategy;
import org.jvnet.jaxb.lang.ToString;
import org.jvnet.jaxb.lang.ToStringStrategy;
import org.jvnet.jaxb.locator.ObjectLocator;

public class MyGeneratedClass implements ToString {
    ...
}
```

**Comment by laurentschoelens** [comment]
This ToString class ?

https://github.com/highsource/jaxb-tools/blob/master/jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/ToString.java

**Comment by laurentschoelens** [comment]
I'll take a look at your sample 😄  Thanks for providing it

**Comment by membersound** [comment]
> This ToString class ?
> 
> https://github.com/highsource/jaxb-tools/blob/master/jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/ToString.java

Exactly, and it is not available on classpath even though I included `jaxb-plugins-runtime`.

**Comment by laurentschoelens** [comment]
Well, I've tried your project and it's working even if you generate your java code from XSD in the `src/main/java` folder which is not a good pratice (you should let it in the `target/generated-sources/xjc` subfolder, or similar folder in `target` folder).

**Comment by laurentschoelens** [comment]
Could you double-check your local copy of `org.jvnet.jaxb:jaxb-plugins-runtime:4.0.8` ?
It might be corrupted in your local .m2 repository folder

**Comment by membersound** [comment]
OMG thank you so much!
Clearing the runtime plugin solved it indeed. Strange that maven did not report about a broken dependency.

**Comment by laurentschoelens** [comment]
It happens sometimes to me too (issue with network), that's why, since the project was working, I'd suggest you to clean up the copy of the jar and rebuild.

And again, you can safely remove the following from your project (it was in the sample) 😄 

```xml
        <dependency>
            <groupId>org.jvnet.jaxb</groupId>
            <artifactId>jaxb-plugins</artifactId>
            <version>4.0.8</version>
        </dependency>
```

**Comment by membersound** [comment]
So but the jaxb-plugins-runtime is still required, right?
Is it maybe sufficient to just add it with `provided` scope? Or is this discouraged?

``` 
       <dependency>
            <groupId>org.jvnet.jaxb</groupId>
            <artifactId>jaxb-plugins-runtime</artifactId>
            <scope>provided</scope>
        </dependency>
```

**Comment by laurentschoelens** [comment]
If you want to use some of the xjc-plugins of jaxb-tools, you only need to add the `jaxb-plugins` artifact in the plugin section.

If you use some of the plugins that generates code based on the `jaxb-plugins-runtime` (which is used by `jaxb-plugins`) classes, you'll need to add the `jaxb-plugins-runtime` dependency in the dependencies section of your project with compile scope.

Whether you need the `jaxb-plugins-runtime` dependency or not should be described in the corresponding wiki section of each plugin. Mainly common used plugins that are in the case of needing the `jaxb-plugins-runtime` are the `toString`, the `equals` and the `hashcode` plugins

**Comment by membersound** [comment]
So in my case the answer is yes, must be compile scope. thnx.

**Comment by laurentschoelens** [comment]
> So in my case the answer is yes, must be compile scope. thnx.

Yes you got it right 👍
