### ISSUE TITLE
[MAVEN_JAXB2_PLUGIN-87] JAXB: generate English Javadoc

### ISSUE THREAD

**Issue by highsource** [highsource/jaxb-tools#7]
See https://java.net/jira/browse/MAVEN_JAXB2_PLUGIN-87.

**Comment by koppor** [comment]
The updated link is https://github.com/highsource/maven-jaxb2-plugin/wiki/Controlling-the-Output

TL;DR: Use following snippet in `<configuration>`:

```xml
          <locale>en</locale>
```

For the googlers: It is **not** the following snipped

```xml
            <arg>-Duser.language=en</arg>
```
