### ISSUE TITLE
[MAVEN_JAXB2_PLUGIN-86] Plugin only generates the first listed execution when using multiple schemas configuration

### ISSUE THREAD

**Issue by highsource** [highsource/jaxb-tools#8]
See https://java.net/jira/browse/MAVEN_JAXB2_PLUGIN-86.

**Comment by pnabbefeld** [comment]
Seems it just doesn't iterate over executions - when I remove the first execution, the second works without cleaning before.

**Comment by laurentschoelens** [comment]
> Seems it just doesn't iterate over executions - when I remove the first execution, the second works without cleaning before.
> Further investigating, I found the following strange behaviour:
> 1. When doing clean & build, only the first sub-package is created.
> 2. When removing the first execution, the remaining packages are created when building.
> 3. When renaming the package of the first execution, all are created.
> It seems there's some strange bug in the logic for testing which packages have to be built.
> 
> I've set "forceRegenerate" for all executions, that works for me.

@pnabbefeld could you share a sample ?
It seems that this issue is no longer a real issue for me with latest version...

**Comment by jhoeflaken** [comment]
Hi,

I still cannot get this to work without _foreceRegenerate_. It seems that the plugin thinks for the seconds execution that everything is already up-to-date. See image below.

![image](https://github.com/highsource/jaxb-tools/assets/4974361/887e3067-3aed-46d3-bbf2-950216b81b02)

This is my configuration:

```
`<plugin>
     <groupId>org.jvnet.jaxb</groupId>
     <artifactId>jaxb-maven-plugin</artifactId>
     <version>4.0.6</version>
     <executions>
          <execution>
              <id>gnl</id>
              <goals>
                  <goal>generate</goal>
              </goals>
              <configuration>
                  <schemaDirectory>src/main/resources/schemas</schemaDirectory>
                  <schemaIncludes>
                      <include>MedMij_Gegevensdienstnamenlijst.1.11.xsd</include>
                  </schemaIncludes>
                  <generatePackage>nl.axians.zorg.dva.list.medmij.gnl</generatePackage>
               </configuration>
        </execution>
        <execution>
            <id>onl</id>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <schemaDirectory>src/main/resources/schemas</schemaDirectory>
                <schemaIncludes>
                    <include>MedMij_OAuthclientlist.5.14.xsd</include>
                </schemaIncludes>
                <generatePackage>nl.axians.zorg.dva.list.medmij.onl</generatePackage>
            </configuration>
        </execution>
    </executions>
</plugin>`
```
I have to XSD which I want to be generated in different packages.

Kind regards,

Jacob

**Comment by laurentschoelens** [comment]
Hi @jhoeflaken 

You should add the following `<generateDirectory>` to each of your configuration, with each having their own values.

Like `<generateDirectory>${project.build.directory}/generated-sources/xjc-gnl</generateDirectory>` for the first one and `<generateDirectory>${project.build.directory}/generated-sources/xjc-onl</generateDirectory>` for the second one.

**Comment by jhoeflaken** [comment]
Hi @laurentschoelens 

Thnx. Works perfectly. Keep up the good work!

Kind regards,

Jacob

**Comment by laurentschoelens** [comment]
> Hi @laurentschoelens 
> 
> Thnx. Works perfectly. Keep up the good work!
> 
> Kind regards,
> 
> Jacob

You're welcome 😃

**Comment by laurentschoelens** [comment]
Closing issue since no example of non working case
